### ISSUE TITLE
Add Apache configuration to README

### ISSUE THREAD

**Issue by HaydenSD** [hystio/web#2]
For easier configuration, we should add a list of settings that have to be changed to run the application.

**Comment by itsgxrney** [comment]
Yes, we should. I'll do that before I go to bed.

**Comment by itsgxrney** [comment]
# Leave a comment. Trailing lines starting with '#' (like these) will be ignored,
# and empty messages will not be submitted. Comments are formatted with GitHub
# Flavored Markdown (GFM):
#
#   http://github.github.com/github-flavored-markdown
#
# On hystio/web issue #2
Done - see #b5dd210.
